name: build-ios-dylib

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Install tools
        run: brew install ldid

      - name: Build dylib only
        run: |
          export THEOS=$HOME/theos
          make

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: BattleCatsMod
          path: .theos/obj/**/*.dylib
